name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: CI='' npm run build --if-present
        env:
          REACT_APP_API_BASE_URL: http://ec2-3-13-142-162.us-east-2.compute.amazonaws.com
          REACT_APP_API_PHOTO: http://ec2-3-13-142-162.us-east-2.compute.amazonaws.com/photos/
          REACT_APP_API_CV: http://ec2-3-13-142-162.us-east-2.compute.amazonaws.com/uploads/
      # - run: npm test
